name: openpelo
description: "Your Machine, Your Apps"
publish_to: 'none'
version: 1.0.62

environment:
    sdk: ">=3.5.0 <4.0.0"
    flutter: ">=3.24.0"

dependencies:
  archive: ^4.0.7
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_adb:
    git:
      url: https://github.com/doudar/flutter_adb.git
  http: ^1.6.0
  intl: ^0.20.2
  multicast_dns: ^0.3.3
  network_info_plus: ^7.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pixel_perfect: ^1.1.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/Icon.png"
    background_color: "#ffffff"
    theme_color: "#B31942"
  windows:
    generate: true
    image_path: "images/Icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "images/Icon.png"

flutter:
  uses-material-design: true
  assets:
    - apps_config.json
    - usb_debug_steps.json
    - wireless_adb_steps.json
    - ADB/
